# Generated by Django 5.0.3 on 2024-03-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('co_autor', models.CharField(max_length=30)),
                ('dara_cadastro', models.DateField()),
                ('emprestado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField()),
                ('tempo_duracao', models.DateField()),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livros')),
            ],
        ),
    ]
