# Generated by Django 5.0.3 on 2024-03-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro'},
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='co_autor',
            new_name='autor',
        ),
    ]
