# Generated by Django 5.0.3 on 2024-03-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_livros_options_rename_co_autor_livros_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='co_autor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
