# Generated by Django 5.0.3 on 2024-03-08 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_livros_dara_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='dara_cadastro',
        ),
        migrations.AddField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
